name: Lint

on: [push]

jobs:
  lint_core:
    name: Lint Core
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
